[summary]
# This will be shown in the title page as "project_name Audit Report"
# As auditors can be formatted further, their names are in lead_auditors.md and assisting_auditors.md
project_name = CAP
report_version = 1.2

# Team_name engaged with CAP Security Cartel to review CAP
team_name = CAP
team_website = https://cap.app/

# Project repository
project_github = https://github.com/cap-labs-dev/cap-contracts.git
initial_commit_hash = ad1f8d772585e3c4ba3d308f7ae72d113554978e
# Optional. Remediation commit hash (leave empty if not applicable)
final_commit_hash = 9819fd7029e5e2ed7b6900cf76fb9bf45be0e319
private_github = https://github.com/cap-security-cartel/security-review-cap-contracts

# Information for Summary table
review_timeline = April 14th - May 2nd
review_methods = Manual Review
