[summary]
# This will be shown in the title page as "project_name Audit Report"
# As auditors can be formatted further, their names are in lead_auditors.md and assisting_auditors.md
project_name = CAP
report_version = 1

# Team_name engaged with CAP Security Cartel to review CAP
team_name = CAP
team_website = https://cap.app/

# Project repository
project_github = https://github.com/cap-labs-dev/cap-contracts
initial_commit_hash = c087fcbd8c7ba9385af9ba142abaa3440169967a
# Optional. Remediation commit hash (leave empty if not applicable)
final_commit_hash = e33283812758dce3c1e9cc4d0858424faa4b2e6e
private_github = https://github.com/cap-security-cartel/security-review-cap-contracts

# Information for Summary table
review_timeline = November 14th
review_methods = Manual Review
